from database import db

def cleanup_all_system_custody_events():
    """
    Removes all calendar events that were automatically generated by the system 
    (type='custody' and createdBy_email='system').
    This fixes the issue where the calendar was flooded with 365+ events.
    """
    print("Starting cleanup of system-generated custody events...")
    
    result = db.events.delete_many({
        "type": "custody",
        "createdBy_email": "system"
    })
    
    print(f"Successfully deleted {result.deleted_count} system-generated custody events.")
    print("User-created custody events have been preserved.")

if __name__ == "__main__":
    cleanup_all_system_custody_events()